[build]
publish = "dist/"
command = "npm run build"

[[redirects]]
from = "/api/*"
to = "https://arzv.herokuapp.com/:splat"
status = 200

[[redirects]]
from = "/api-dev/*"
to = "http://localhost:3000/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
