[build]
publish = "dist/"
command = "npm run build && cd functions && npm ci"
functions = "functions"

[[redirects]]
from = "/proxy/*"
to = "https://:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
